console.log("*******************************************************")
console.log("*                    Report Card                      *")
console.log("*******************************************************")
console.log("* Name        : Nidhi Dubey                           *")
console.log("* Roll Number : 23                                    *")
console.log("*******************************************************")
console.log("* Subject            *  Max Marks   * Marks Obtained  *")
console.log("*******************************************************")
console.log("* Mathematics        *  100         *  85             *")
console.log("* Science            *  100         *  90             *")
console.log("* English            *  100         *  88             *")
console.log("* Social Studies     *  100         *  75             *")
console.log("* Physical Education *  100         *  95             *")
console.log("*******************************************************")
console.log("* Total              *  500         *  433            *")
console.log("* Percentage         : 86.6%                          *")
console.log("*******************************************************")
console.log("* Status: Pass                                        *")
console.log("*******************************************************")